done
stepancar-web-programming/2023-fall-lab-portfolio-nasibullin-a.-m. pull request #7
Opened 2023-11-19 18:13 UTC by lm-cyber

2023-11-19 18:14 UTC, lm-cyber commented
я не могу пушить, не могу сменить defalut ветку, поэтому сделал эти кульбиты

2023-12-06 23:38 UTC, stepancar commented
@lm-cyber , приложите пожалуйста ссылку на собранную демку в описании PR или README или package.json

2024-01-04 04:39 UTC, stepancar requested changes
Не получил ссылку на демо

2024-01-04 04:40 UTC, stepancar commented on tailwind.config.js
> +        // },
Пожалуйста, подготовьте ПР к ревью

2024-01-04 04:43 UTC, stepancar commented
lint не проходит
```
stepancar@Ezras-MBP 2023-fall-lab-portfolio-nasibullin-a.-m. % yarn lint
yarn run v1.22.21
$ eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .

/Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/components/UI/Article/index.tsx
  10:46  error  Replace `text-gray-600·pb-4·text-2xl` with `pb-4·text-2xl·text-gray-600`  prettier/prettier

/Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/pages/Landing/index.tsx
  9:37  error  Replace `bg-blue-400·rounded-full` with `rounded-full·bg-blue-400`  prettier/prettier


/Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/pages/Resume/index.tsx
  67:50  error  Replace `bg-gray-300·w-max·rounded` with `w-max·rounded·bg-gray-300`  prettier/prettier

✖ 3 problems (3 errors, 0 warnings)
  3 errors and 0 warnings potentially fixable with the `--fix` option.
```

2024-01-04 04:47 UTC, stepancar commented on src/view/pages/Resume/data.ts
> +        '+7 (999) 1648392\n' +
Давайте сделаем чтобы при нажатии на телефон открывался диалог звонка, для почты - стандартный почтовый клиент

2024-01-04 04:53 UTC, stepancar commented
Хорошая работа. давайте на защиту исправим мелочи указанные выше и добавим github action, который запукает lint чтобы нельзя было смержить пока не пройдена проверка.  Дал вам права админа на этот репозиторий

2024-01-17 20:41 UTC, lm-cyber commented
> @lm-cyber , приложите пожалуйста ссылку на собранную демку в описании PR или README или package.json

https://web-nero.onrender.com/

2024-01-17 20:45 UTC, lm-cyber commented on tailwind.config.js
> +        // },
fix

2024-01-17 20:46 UTC, lm-cyber commented
> lint не проходит
> 
> ```
> stepancar@Ezras-MBP 2023-fall-lab-portfolio-nasibullin-a.-m. % yarn lint
> yarn run v1.22.21
> $ eslint . --ext ts,tsx --report-unused-disable-directives --max-warnings 0
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
> 
> /Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/components/UI/Article/index.tsx
>   10:46  error  Replace `text-gray-600·pb-4·text-2xl` with `pb-4·text-2xl·text-gray-600`  prettier/prettier
> 
> /Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/pages/Landing/index.tsx
>   9:37  error  Replace `bg-blue-400·rounded-full` with `rounded-full·bg-blue-400`  prettier/prettier
> 
> 
> /Users/stepancar/Desktop/projects/2023-fall-lab-portfolio-nasibullin-a.-m./src/view/pages/Resume/index.tsx
>   67:50  error  Replace `bg-gray-300·w-max·rounded` with `w-max·rounded·bg-gray-300`  prettier/prettier
> 
> ✖ 3 problems (3 errors, 0 warnings)
>   3 errors and 0 warnings potentially fixable with the `--fix` option.
> ```
fix

2024-01-17 20:54 UTC, lm-cyber commented
я в dev запушить не могу

2024-01-17 23:14 UTC, stepancar approved these changes

2024-01-17 23:16 UTC, merged

2024-01-18 11:21 UTC, lm-cyber commented
я добавил открытие почтового клиента и звонка для номера телефона